name: pytest

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    types: [ ready_for_review, opened, synchronize, reopened, converted_to_draft ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Load cached venv
      id: cached-venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}

    - name: Install uv
      if: steps.cached-venv.outputs.cache-hit != 'true'
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      if: steps.cached-venv.outputs.cache-hit != 'true'
      run: uv sync --all-extras --dev

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest tests/
